### ISSUE TITLE
Fix layout reflows on Speakers page

### ISSUE THREAD

**Issue by zekefarwell** [vtcodecamp/www.vtcodecamp.org#5]
When you follow a link with a url fragment directly to a speakers profile (https://www.vtcodecamp.org/2019/speakers/#kyle-mitofsky) the correct speaker isn't always in the viewport until after all the images have loaded and the layout re-flowed to reflect them.   Probably could be resolved with image dimensions being preset in css so the browser wouldn't have to wait for them all to download before it can layout properly.

**Comment by KyleMit** [comment]
We can pull the img dimensions during build using [npm image-size](https://www.npmjs.com/package/image-size)

Here's [an issue](https://github.com/VermontDepartmentOfHealth/docs/issues/100) where I worked on adding it to a markdown layer as each image is processed, but it's probably even easier if we're starting with a json object with image paths.

And here's the [actual commit with changes](https://github.com/VermontDepartmentOfHealth/docs/commit/6e60fed569a4a605621daa169c636db41673b8f2)

**Comment by zekefarwell** [comment]
Looks like this was fixed last fall in commit 2db8ba62f3e59b2852e11e1d2d61e2fd852fe3ea.
